### ISSUE TITLE
Create a new reminder

### ISSUE THREAD

**Issue by stevekinney** [turingschool-projects/1606-remember-2#5]
Users should be able to create new note.

- At the bottom of the `reminders.hbs` template, there is a button that routes the use to `/new` where they can create a new reminder.
- The new reminder should have inputs for the title, date, and notes.
- The new reminder should have a button for submitting the new note.
- Pressing the button, should submit reminder to the database and have it shown in the `Reminders` list.

There are no tests set up for this user story. So, you'll have to write an acceptance test.

**Comment by blakeworsley** [comment]
We have called our "reminders" "reminder-list", would you like us to change it, or is it ok?

**Comment by blakeworsley** [comment]
Closes #5

**Comment by martensonbj** [comment]
Merged. Closing issue.
